### ISSUE TITLE
** import 'package:space_client_app/amplifyconfiguration.dart'; ** not found

### ISSUE THREAD

**Issue by Rhythm-08** [antonio-pedro99/file-space-mobile-app#23]
I was running this project on my device but in your  " lib/services/aws.dart file" on the 6th line 
import 'package:space_client_app/amplifyconfiguration.dart';  doesn't exist.
 
I don't know if this problem is from my side or a genuine issue please confirm.

![issue](https://user-images.githubusercontent.com/64489317/209213018-b5df071a-9ee2-4872-9692-e0d0117c1b1c.png)

**Comment by antonio-pedro99** [comment]
Hello @Rhythm-08, thanks for showing interest.
This file is  auto generated by AWS CLI. Please follow the steps to get started with  [AWS CLI](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter/#4-initialize-amplify-in-the-application)
Note: You will need an AWS account(create one [here](https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2Fhome%3FhashArgs%3D%2523%26isauthcode%3Dtrue%26nc2%3Dh_ct%26src%3Dheader-signin%26state%3DhashArgsFromTB_ap-northeast-1_c3c989cff8374936&client_id=arn%3Aaws%3Asignin%3A%3A%3Aconsole%2Fcanvas&forceMobileApp=0&code_challenge=s_FgfNET-YZdc0pIpHdZd7fDOt4EtFugOJfTCF-XWCM&code_challenge_method=SHA-256)

**Comment by Rhythm-08** [comment]
@antonio-pedro99, Thank you for explaining.

**Comment by antonio-pedro99** [comment]
@Rhythm-08  welcome!
Please report any issue if found.
